; these are the palette hex values and the colors they represent
DARK_GRAY           = $00
MEDIUM_GRAY         = $10
LIGHT_GRAY          = $20
LIGHTEST_GRAY       = $30

DARK_BLUE           = $01
MEDIUM_BLUE         = $11
LIGHT_BLUE          = $21
LIGHTEST_BLUE       = $31

DARK_INDIGO         = $02
MEDIUM_INDIGO       = $12
LIGHT_INDIGO        = $22
LIGHTEST_INDIGO     = $32

DARK_VIOLET         = $03
MEDIUM_VIOLET       = $13
LIGHT_VIOLET        = $23
LIGHTEST_VIOLET     = $33

DARK_PURPLE         = $04
MEDIUM_PURPLE       = $14
LIGHT_PURPLE        = $24
LIGHTEST_PURPLE     = $34

DARK_REDVIOLET      = $05
MEDIUM_REDVIOLET    = $15
LIGHT_REDVIOLET     = $25
LIGHTEST_REDVIOLET  = $35

DARK_RED            = $06
MEDIUM_RED          = $16
LIGHT_RED           = $26
LIGHTEST_RED        = $36

DARK_ORANGE         = $07
MEDIUM_ORANGE       = $17
LIGHT_ORANGE        = $27
LIGHTEST_ORANGE     = $37

DARK_YELLOW         = $08
MEDIUM_YELLOW       = $18
LIGHT_YELLOW        = $28
LIGHTEST_YELLOW     = $38

DARK_CHARTREUSE     = $09
MEDIUM_CHARTREUSE   = $19
LIGHT_CHARTREUSE    = $29
LIGHTEST_CHARTREUSE = $39

DARK_GREEN          = $0A
MEDIUM_GREEN        = $1A
LIGHT_GREEN         = $2A
LIGHTEST_GREEN      = $3A

DARK_CYAN           = $0B
MEDIUM_CYAN         = $1B
LIGHT_CYAN          = $2B
LIGHTEST_CYAN       = $3B

DARK_TURQUOISE      = $0C
MEDIUM_TURQUOISE    = $1C
LIGHT_TURQUOISE     = $2C
LIGHTEST_TURQUOISE  = $3C

BLACK               = $0F
DARKEST_GRAY        = $2D
MEDIUM_GRAY2        = $3D

;.segment "ROMDATA"
;palette_background:
;.byte BLACK, LIGHTEST_YELLOW, MEDIUM_ORANGE,     DARK_ORANGE
;.byte BLACK, DARK_CHARTREUSE, MEDIUM_CHARTREUSE, LIGHT_CHARTREUSE
;.byte BLACK, DARK_BLUE,       MEDIUM_BLUE,       LIGHT_BLUE
;.byte BLACK, DARK_GRAY,       MEDIUM_GRAY,       LIGHTEST_GRAY

;palette_sprites:
;.byte BLACK, LIGHTEST_YELLOW, LIGHT_ORANGE, MEDIUM_ORANGE
;.byte BLACK, MEDIUM_PURPLE,   LIGHT_PURPLE, LIGHTEST_PURPLE
;.byte BLACK, MEDIUM_CYAN,     LIGHT_CYAN,   LIGHTEST_CYAN
;.byte BLACK, MEDIUM_INDIGO,   LIGHT_INDIGO, LIGHTEST_INDIGO

