.enum
    EMPTY               ; INVENTORYLIST
    BigBag
    PhoneCard
    Crumbs
    RepelRing
    ButterKnife         = $0A
    SurvKnife
    Sword
    Katana
    StunGun
    AirGun
    PlasticBat
    WoodenBat
    AluminumBat
    HanksBat
    FryingPan
    NonstickPan
    IronSkillet
    Slingshot
    Boomerang
    Insecticide
    SuperSpray
    FleaBag
    WordsOLove
    SwearWords
    StkyMachine
    Flashdark
    StoneOrigin
    PoisnNeedle
    FlThrower
    Bomb
    SuperBomb
    LaserBeam
    PlasmaBeam
    Rope                = $28
    PeaceCoin           = $2D
    ProtectCoin
    MagicCoin
    BrassRing
    SilverRing
    GoldRing
    H2oPendant
    FirePendant
    EarthPendnt
    SeaPendant
    OrangeJuice         = $3C
    FrenchFries
    MagicHerb
    Hamburger
    SportsDrink
    LifeUpCream
    AsthmaSpray
    Antidote
    Mouthwash
    BerryTofu
    Bread               = $47
    NobleSeed
    PSIStone
    MagicRibbon         = $4B
    MagicCandy
    QuickCapsul         = $4E
    WisdomCaps
    PhysicalCap
    ForceCapsul
    FightCapsul
    BasementKey         = $55
    ZooKey
    GhostKey
    GGFsDiary
    Pass
    Ticket
    CanaryChick         = $5F
    BottlRocket         = $61
    Hat
    Dentures
    TicketStub
    ICchip
    Ocarina
    FranklnBdge         = $68
    FrndshpRing
    OnyxHook            = $6B
    LastWeapon
    Ruler
    CashCard
    RedWeed
    Bullhorn
    Map
    Debug               = $7F
    MyHome
    Podunk
    Merrysville
    Reindeer1
    Spookane1
    Snowman1
    Youngtown
    Ellay
    Reindeer2           = $90
    Spookane2
    Snowman2
    Union1
    Union2
    Union3
    Spookane3
    Snowman3
    Reindeer3
    Snowman4
    Reindeer4
    Spookane4
    FlightplanA
    FlightplanB
    FlightplanC
    Hint1
    Hint2
    Hint3
    RealRocket          = $A6
    TimeMachine
.endenum