.charmap ' ', $A0
.charmap '!', $A1
.charmap '?', $A2
.charmap '#', $A3      ; ".."
.charmap '$', $A4
.charmap '*', $A5
.charmap '"', $A6
.charmap $27, $A7
.charmap '(', $A8
.charmap ')', $A9
.charmap ':', $AA
.charmap ';', $AB
.charmap ',', $AC
.charmap '-', $AD
.charmap '.', $AE
.charmap '/', $AF

.charmap '0', $B0
.charmap '1', $B1
.charmap '2', $B2
.charmap '3', $B3
.charmap '4', $B4
.charmap '5', $B5
.charmap '6', $B6
.charmap '7', $B7
.charmap '8', $B8
.charmap '9', $B9
; special simbols

.charmap '@', $C0
.charmap 'A', $C1
.charmap 'B', $C2
.charmap 'C', $C3
.charmap 'D', $C4
.charmap 'E', $C5
.charmap 'F', $C6
.charmap 'G', $C7
.charmap 'H', $C8
.charmap 'I', $C9
.charmap 'J', $CA
.charmap 'K', $CB
.charmap 'L', $CC
.charmap 'M', $CD
.charmap 'N', $CE
.charmap 'O', $CF
.charmap 'P', $D0
.charmap 'Q', $D1
.charmap 'R', $D2
.charmap 'S', $D3
.charmap 'T', $D4
.charmap 'U', $D5
.charmap 'V', $D6
.charmap 'W', $D7
.charmap 'X', $D8
.charmap 'Y', $D9
.charmap 'Z', $DA

; frame fields $DB-DF and arrow $E0

.charmap 'a', $E1
.charmap 'b', $E2
.charmap 'c', $E3
.charmap 'd', $E4
.charmap 'e', $E5
.charmap 'f', $E6
.charmap 'g', $E7
.charmap 'h', $E8
.charmap 'i', $E9
.charmap 'j', $EA
.charmap 'k', $EB
.charmap 'l', $EC
.charmap 'm', $ED
.charmap 'n', $EE
.charmap 'o', $EF
.charmap 'p', $F0
.charmap 'q', $F1
.charmap 'r', $F2
.charmap 's', $F3
.charmap 't', $F4
.charmap 'u', $F5
.charmap 'v', $F6
.charmap 'w', $F7
.charmap 'x', $F8
.charmap 'y', $F9
.charmap 'z', $FA

; frame fields $FB-FF