AttributeCopy       = $6600

Counter             = $6707

InfoCharacter       = $6710

CurrentGame         = $7400

Boy1Lvl             = $7450

Boy1Name            = $7478

GirlName            = $74B8

Boy2Name            = $74F8

Boy3Name            = $7538

FoodName            = $7689

Boy1LvlSave1        = $7750

Boy1NameSave1       = $7778

Boy1LvlSave2        = $7A50

Boy1NameSave2       = $7A78

Boy1LvlSave3        = $7D50

Boy1NameSave3       = $7D78